# Generated by Django 5.2.1 on 2025-05-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form',
            new_name='contactform',
        ),
    ]
